apiVersion: v1
kind: Service
metadata:
  name: flask-spam-service
spec:
  type: LoadBalancer
  selector:
    app: flask-spam-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001